# Generated by Django 5.2.8 on 2026-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_url', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
