# Generated by Django 6.0.2 on 2026-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_url', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('Anime', 'Anime'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy')], default='Action', max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
