# Generated by Django 6.0.2 on 2026-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='video/'),
            preserve_default=False,
        ),
    ]
